# Generated by Django 5.0.6 on 2024-06-22 21:20

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=255)),
                ('protocolo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='DadosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('cnpj', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=14)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=10)),
                ('cod_ibge', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nacimento', models.CharField(max_length=100)),
                ('rg', models.ImageField(blank=True, null=True, upload_to=base.models.upload_image_book)),
                ('carteira_identidade', models.ImageField(blank=True, null=True, upload_to=base.models.upload_image_book)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pedidos')),
            ],
        ),
    ]
