# Generated by Django 5.0.6 on 2024-07-05 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('numero', models.IntegerField(default=1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='voucher',
            name='lote',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.lote'),
            preserve_default=False,
        ),
    ]
