# Generated by Django 5.0.6 on 2024-06-23 12:03

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_dadoscliente_voucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadoscliente',
            old_name='rg',
            new_name='rg_frente',
        ),
        migrations.AddField(
            model_name='dadoscliente',
            name='rg_verso',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_image_book),
        ),
    ]
