# Generated by Django 5.0.6 on 2024-07-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_dadoscliente_carteira_habilitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('1', 'Emissão liberada'), ('2', 'Protocolo Gerado'), ('3', 'Emitida')], default='P', max_length=1),
        ),
    ]
