# Generated by Django 5.0.6 on 2024-07-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pedidos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Emissão liberada'), ('2', 'Protocolo Gerado'), ('3', 'Emitida')], default='1', max_length=1, null=True),
        ),
    ]
