# Generated by Django 5.0.6 on 2024-06-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashSlot', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='hashVenda',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
