# Generated by Django 5.0.6 on 2024-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_pedidos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='hashVenda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pedido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='protocolo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Não Confirmada'), ('2', 'Solicitação de Estorno'), ('3', 'Estornada'), ('4', 'Emissão liberada'), ('5', 'Protocolo Gerado'), ('6', 'Emitida'), ('7', 'Revogada'), ('8', 'Em Verificação'), ('9', 'Em Validação'), ('11', 'Recusada'), ('12', 'Cancelada'), ('13', 'Atribuído a Voucher')], default='1', max_length=2, null=True),
        ),
    ]
