# Generated by Django 5.0.6 on 2024-10-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_dadoscliente_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadoscliente',
            name='carteira_habilitacao',
        ),
        migrations.RemoveField(
            model_name='dadoscliente',
            name='rg_frente',
        ),
        migrations.RemoveField(
            model_name='dadoscliente',
            name='rg_verso',
        ),
        migrations.AddField(
            model_name='dadoscliente',
            name='possui_cnh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Não Confirmada'), ('2', 'Solicitação de Estorno'), ('3', 'Estornada'), ('4', 'Emissão liberada'), ('5', 'Protocolo Gerado'), ('6', 'Emitida'), ('7', 'Revogada'), ('8', 'Em Verificação'), ('9', 'Em Validação'), ('10', 'Recusada'), ('11', 'Cancelada'), ('12', 'Atribuído a Voucher')], default='1', max_length=2, null=True),
        ),
    ]
