# Generated by Django 5.0.6 on 2024-10-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_dadoscliente_carteira_habilitacao_and_more'),
        ('base', '0009_voucher_tipo_certificado_alter_pedidos_status_and_more'),
    ]

    operations = [
    ]
