# Generated by Django 5.0.6 on 2024-10-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_merge_20241027_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='tipo_certificado',
        ),
        migrations.AddField(
            model_name='voucher',
            name='tipo',
            field=models.CharField(choices=[('ECNPJ', 'e-CNPJ'), ('ECPF', 'e-CPF')], default='ECNPJ', max_length=5),
        ),
        migrations.AlterField(
            model_name='dadoscliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='lote',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.lote'),
            preserve_default=False,
        ),
    ]
