# Generated by Django 5.0.6 on 2024-10-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_voucher_tipo_certificado_voucher_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='entregue',
            field=models.BooleanField(default=False),
        ),
    ]
